# Generated by Django 4.1.7 on 2023-03-26 17:46

from django.db import migrations
from django.contrib.auth.models import Group

def make_groups(apps, schema_editor):
    _mod_group, mod_created = Group.objects.get_or_create(name='Moderator')
    _sub_group, sub_created = Group.objects.get_or_create(name='Subscriber')
    if not all((mod_created,sub_created)):
        raise Exception("Couldn't create necessary groups, please add them from Admin panel")



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(make_groups)
    ]
